tasks:
  - name: build
    init: ./gradlew build && sync-done build
  - name:  keycloak
    init: gp sync-await build && ./gradlew bootRun
  - name: clients
    init: gp await-port 8080 && ./gradlew :kctest-ktor:run
ports:
  - port: 8080
    onOpen: open-browser
  - port: 9090
    onOpen: open-browser
