tasks:
  - name:  build
    init: ./gradlew build
    command: gp sync-done build
  - name:  keycloak
    init: gp sync-await build
    command: ./gradlew bootRun
  - name: clients
    init: gp sync-await build
    command: ./gradlew :kctest-ktor:run
